#!/usr/bin/env bun
// scripts/build-prototools.ts
// Reads site/plugins.jsonld and writes a .prototools.test file wiring every
// plugin (or just those listed in $CHANGED) to its local file path,
// with each tool pinned to "latest" at the top level, for CI
// smoke-testing `proto install`.

import { readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'

type Entry = {
  identifier?: string
  pluginFile?: string
  url?: string
  downloadUrl?: string
}

type Catalog = { plugins?: Entry[] }

const root = resolve(import.meta.dir, '..')
const pluginsDir = join(root, 'plugins')
const catalogFile = process.env.CATALOG ?? join(root, 'site', 'plugins.jsonld')
const outFile = join(root, '.prototools.test')

const changed = (process.env.CHANGED ?? '').split(/\s+/).filter(Boolean)

const catalog = JSON.parse(await readFile(catalogFile, 'utf8')) as Catalog
const plugins = Array.isArray(catalog.plugins) ? catalog.plugins : []

const filenameFromUrl = (url: string) => {
  try {
    return new URL(url).pathname.split('/').pop() ?? ''
  } catch {
    return url.split('/').pop() ?? ''
  }
}

const toEntry = (plugin: Entry) => {
  const id = plugin.identifier
  if (!id) return null
    const source = plugin.pluginFile || plugin.downloadUrl || plugin.url || ''
    const file = filenameFromUrl(source) || `${id}.toml`
    return { id, file }
}

const allEntries = plugins
.map(toEntry)
.filter((entry): entry is { id: string; file: string } => entry !== null)

const entries = (changed.length
? allEntries.filter((entry) => changed.includes(entry.id))
: allEntries
).sort((a, b) => a.id.localeCompare(b.id))

if (entries.length === 0) {
  console.log('no plugins to write (CHANGED filtered everything out)')
  await writeFile(outFile, '', 'utf8')
  process.exit(0)
}

const versionLines = entries.map((entry) => `${entry.id} = "latest"`).join('\n')

const pluginLines = entries
.map((entry) => `${entry.id} = "file://${pluginsDir}/${entry.file}"`)
.join('\n')

const body = `# Generated by scripts/build-prototools.ts
# Smoke-test config for the hosted plugin catalog.

${versionLines}

[settings]
# disabled to avoid polluting their data with our testing / CI runs
telemetry = false

[plugins]
${pluginLines}
`

await writeFile(outFile, body, 'utf8')

console.log(`wrote ${entries.length} plugin(s) → ${outFile}`)
if (changed.length) console.log(`filter: CHANGED=${changed.join(' ')}`)
