#!/usr/bin/env bun
// scripts/build-prototools.ts
// Reads plugins/*.toml and writes a .prototools.test file wiring every
// plugin (or just those listed in $CHANGED) to its local file path,
// for CI smoke-testing `proto install`.

import { readdir, writeFile } from 'node:fs/promises'
import { basename, extname, join, resolve } from 'node:path'

const root = resolve(import.meta.dir, '..')
const pluginsDir = join(root, 'plugins')
const outFile = join(root, '.prototools.test')

const changed = (process.env.CHANGED ?? '').split(/\s+/).filter(Boolean)

const allIds = (await readdir(pluginsDir))
    .filter(f => f.endsWith('.toml'))
    .map(f => basename(f, extname(f)))

const ids = (changed.length ? allIds.filter(id => changed.includes(id)) : allIds).sort()

if (ids.length === 0) {
    console.log('no plugins to write (CHANGED filtered everything out)')
    await writeFile(outFile, '', 'utf8')
    process.exit(0)
}

const body = `# Generated by scripts/build-prototools.ts
# Smoke-test config for the hosted plugin catalog.

[settings]
# disabled to avoid polluting their data with our testing / CI runs
telemetry = false

[plugins]
${ids.map(id => `${id} = "schema:file://${pluginsDir}/${id}.toml"`).join('\n')}
`

await writeFile(outFile, body, 'utf8')

console.log(`wrote ${ids.length} plugin(s) → ${outFile}`)
if (changed.length) console.log(`filter: CHANGED=${changed.join(' ')}`)
