#!/usr/bin/env bun
// scripts/build-prototools.ts
// Reads plugins/*.toml and writes a .prototools.test file wiring every
// plugin to its hosted site URL, for CI smoke-testing `proto install`.

import { readdir, writeFile } from 'node:fs/promises'
import { basename, extname, join, resolve } from 'node:path'

const root = resolve(import.meta.dir, '..')
const pluginsDir = join(root, 'plugins')
const outFile = join(root, '.prototools.test')
const baseUrl = (process.env.BASE_URL ?? 'https://tomdavidson.github.io/proto').replace(/\/+$/, '')

const files = (await readdir(pluginsDir))
    .filter(f => f.endsWith('.toml'))
    .sort()

const ids = files.map(f => basename(f, extname(f)))

const body = `# Generated by scripts/build-prototools.ts
# Smoke-test config for the hosted plugin catalog.

[settings]
# disabled to avoid polluting their data with our testing / CI runs
telemetry = false

[plugins]
${ids.map(id => `${id} = "schema:${baseUrl}/${id}.toml"`).join('\n')}
`

await writeFile(outFile, body, 'utf8')

console.log(`wrote ${ids.length} plugins → ${outFile}`)
